# Generated by Django 5.2.1 on 2025-05-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='worked_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
